import { pool, DTO } from '../../../global/database';

const ignoredQueriesUpperCase = ['SHOW FULL PROCESSLIST', 'SHOW GLOBAL STATUS', 'SHOW GLOBAL VARIABLES'];

export class DatabaseService {
    private async queryDatabaseStats() {
        const connection = await pool.getConnection();
        try {

            let status = {
                questions: 0,
                com_select: 0,
                com_insert: 0,
                com_update: 0,
                com_delete: 0,
                slow_queries: 0,
                threads_connected: 0,
                threads_running: 0,
                connections: 0,
                aborted_connects: 0,
                max_used_connections: 0,
                innodb_buffer_pool_bytes_data: 0,
                innodb_buffer_pool_read_requests: 0,
                innodb_buffer_pool_write_requests: 0,
                innodb_pages_read: 0,
                innodb_pages_written: 0,
                table_open_cache_hits: 0,
                table_open_cache_misses: 0,
                select_full_join: 0,
                select_scan: 0,
                created_tmp_tables: 0,
                created_tmp_disk_tables: 0,
                uptime: 0
            };
            let processes = [
                {
                    id: 0,
                    user: '',
                    host: '',
                    db: '',
                    command: '',
                    time: 0,
                    state: '',
                    info: ''
                }
            ];
            let variables = {
                max_connections: 0,
                threads_connected: 0,
                threads_running: 0,
                connections: 0,
                aborted_connects: 0,
                max_used_connections: 0,
                innodb_buffer_pool_size: 0,
                innodb_buffer_pool_bytes_data: 0,
                innodb_buffer_pool_read_requests: 0,
                innodb_buffer_pool_write_requests: 0,
                innodb_pages_read: 0,
                innodb_pages_written: 0,
                table_open_cache_hits: 0,
                table_open_cache_misses: 0,
                select_full_join: 0,
                select_scan: 0,
                created_tmp_tables: 0,
                created_tmp_disk_tables: 0,
                version: ""
            };

            const resultGlobalStatus = await new DTO({
                query: 'SHOW GLOBAL STATUS',
                connection
            }).query();

            const resultProcessList = await new DTO({
                query: 'SHOW FULL PROCESSLIST',
                connection
            }).query();

            const resultVariables = await new DTO({
                query: 'SHOW GLOBAL VARIABLES',
                connection
            }).query();

            if (resultGlobalStatus.success) {
                status = resultGlobalStatus.data.reduce((acc: any, row: any) => {
                    acc[row.Variable_name.toLowerCase()] = row.Value;
                    return acc;
                }, {});
            }

            if (resultVariables.success) {
                variables = resultVariables.data.reduce((acc: any, row: any) => {
                    acc[row.Variable_name.toLowerCase()] = row.Value;
                    return acc;
                }, {});
            }

            if (resultProcessList.success) {
                processes = resultProcessList.data as any[];
            }

            return { status, processes, variables };
        } finally {
            connection.release();
        }
    }

    public async getDatabaseStats() {
        const { status, processes, variables } = await this.queryDatabaseStats();

        // Filter out monitoring queries from process list
        const filteredProcesses = processes.filter((p: any) => {
            const info = p.Info || '';
            return !ignoredQueriesUpperCase.some(query => info.includes(query));
        });

        // Calculate query statistics using actual metrics
        const queries = {
            total: Number(status.questions || 0),
            selects: Number(status.com_select || 0),
            inserts: Number(status.com_insert || 0),
            updates: Number(status.com_update || 0),
            deletes: Number(status.com_delete || 0),
            slow: Number(status.slow_queries || 0)
        };

        // Calculate connection statistics
        const connections = {
            max: Number(variables.max_connections || 0),
            current: Number(status.threads_connected || 0),
            active: Number(status.threads_running || 0),
            total: Number(status.connections || 0),
            aborted: Number(status.aborted_connects || 0),
            maxUsed: Number(status.max_used_connections || 0)
        };

        // Process InnoDB statistics using actual metrics
        const innodb = {
            bufferPoolSize: Number(variables.innodb_buffer_pool_size || 0),
            bufferPoolUsed: Number(status.innodb_buffer_pool_bytes_data || 0),
            readRequests: Number(status.innodb_buffer_pool_read_requests || 0),
            writeRequests: Number(status.innodb_buffer_pool_write_requests || 0),
            pagesRead: Number(status.innodb_pages_read || 0),
            pagesWritten: Number(status.innodb_pages_written || 0)
        };

        // Process performance metrics
        const performance = {
            tableOpenCacheHits: Number(status.table_open_cache_hits || 0),
            tableCacheMisses: Number(status.table_open_cache_misses || 0),
            fullJoinScans: Number(status.select_full_join || 0),
            fullTableScans: Number(status.select_scan || 0),
            tmpTablesCreated: Number(status.created_tmp_tables || 0),
            tmpTablesOnDisk: Number(status.created_tmp_disk_tables || 0),
        };

        return {
            queries,
            connections,
            innodb,
            performance,
            processes: filteredProcesses.map((p: any) => ({
                id: p.Id,
                user: p.User,
                host: p.Host,
                db: p.db,
                command: p.Command,
                time: p.Time,
                state: p.State,
                info: p.Info
            })),
            uptime: Number(status.uptime || 0),
            version: variables.version,
            timestamp: new Date().toISOString()
        };
    }
}

/* const data = {
    aborted_clients: '43',
    aborted_connects: '0',
    aborted_connects_preauth: '0',
    access_denied_errors: '0',
    acl_column_grants: '0',
    acl_database_grants: '0',
    acl_function_grants: '0',
    acl_procedure_grants: '0',
    acl_package_spec_grants: '0',
    acl_package_body_grants: '0',
    acl_proxy_users: '2',
    acl_role_grants: '0',
    acl_roles: '0',
    acl_table_grants: '1',
    acl_users: '5',
    aria_pagecache_blocks_not_flushed: '0',
    aria_pagecache_blocks_unused: '15635',
    aria_pagecache_blocks_used: '14',
    aria_pagecache_read_requests: '5639',
    aria_pagecache_reads: '633',
    aria_pagecache_write_requests: '960',
    aria_pagecache_writes: '960',
    aria_transaction_log_syncs: '0',
    binlog_commits: '0',
    binlog_group_commits: '0',
    binlog_group_commit_trigger_count: '0',
    binlog_group_commit_trigger_lock_wait: '0',
    binlog_group_commit_trigger_timeout: '0',
    binlog_snapshot_file: '',
    binlog_snapshot_position: '0',
    binlog_bytes_written: '0',
    binlog_cache_disk_use: '0',
    binlog_cache_use: '0',
    binlog_stmt_cache_disk_use: '0',
    binlog_stmt_cache_use: '0',
    busy_time: '0.000000',
    bytes_received: '768552',
    bytes_sent: '12485190',
    column_compressions: '0',
    column_decompressions: '0',
    com_admin_commands: '0',
    com_alter_db: '0',
    com_alter_db_upgrade: '0',
    com_alter_event: '0',
    com_alter_function: '0',
    com_alter_procedure: '0',
    com_alter_server: '0',
    com_alter_sequence: '0',
    com_alter_table: '0',
    com_alter_user: '0',
    com_analyze: '0',
    com_assign_to_keycache: '0',
    com_backup: '0',
    com_backup_lock: '0',
    com_begin: '1',
    com_binlog: '0',
    com_call_procedure: '0',
    com_change_db: '408',
    com_change_master: '0',
    com_check: '0',
    com_checksum: '0',
    com_commit: '1',
    com_compound_sql: '0',
    com_create_db: '1',
    com_create_event: '0',
    com_create_function: '0',
    com_create_index: '3',
    com_create_package: '0',
    com_create_package_body: '0',
    com_create_procedure: '0',
    com_create_role: '0',
    com_create_sequence: '0',
    com_create_server: '0',
    com_create_table: '6',
    com_create_temporary_table: '0',
    com_create_trigger: '0',
    com_create_udf: '0',
    com_create_user: '0',
    com_create_view: '0',
    com_dealloc_sql: '0',
    com_delete: '7',
    com_delete_multi: '0',
    com_do: '0',
    com_drop_db: '0',
    com_drop_event: '0',
    com_drop_function: '0',
    com_drop_index: '0',
    com_drop_procedure: '0',
    com_drop_package: '0',
    com_drop_package_body: '0',
    com_drop_role: '0',
    com_drop_server: '0',
    com_drop_sequence: '0',
    com_drop_table: '0',
    com_drop_temporary_table: '0',
    com_drop_trigger: '0',
    com_drop_user: '0',
    com_drop_view: '0',
    com_empty_query: '0',
    com_execute_immediate: '0',
    com_execute_sql: '0',
    com_flush: '0',
    com_get_diagnostics: '0',
    com_grant: '0',
    com_grant_role: '0',
    com_ha_close: '0',
    com_ha_open: '0',
    com_ha_read: '0',
    com_help: '0',
    com_insert: '18',
    com_insert_select: '0',
    com_install_plugin: '0',
    com_kill: '0',
    com_load: '0',
    com_lock_tables: '0',
    com_optimize: '0',
    com_preload_keys: '0',
    com_prepare_sql: '0',
    com_purge: '0',
    com_purge_before_date: '0',
    com_release_savepoint: '0',
    com_rename_table: '0',
    com_rename_user: '0',
    com_repair: '0',
    com_replace: '5',
    com_replace_select: '0',
    com_reset: '0',
    com_resignal: '0',
    com_revoke: '0',
    com_revoke_all: '0',
    com_revoke_role: '0',
    com_rollback: '0',
    com_rollback_to_savepoint: '0',
    com_savepoint: '0',
    com_select: '8872',
    com_set_option: '370',
    com_show_authors: '0',
    com_show_binlog_events: '0',
    com_show_binlogs: '2',
    com_show_charsets: '0',
    com_show_collations: '0',
    com_show_contributors: '0',
    com_show_create_db: '0',
    com_show_create_event: '0',
    com_show_create_func: '0',
    com_show_create_package: '0',
    com_show_create_package_body: '0',
    com_show_create_proc: '0',
    com_show_create_table: '18',
    com_show_create_trigger: '0',
    com_show_create_user: '0',
    com_show_databases: '0',
    com_show_engine_logs: '0',
    com_show_engine_mutex: '0',
    com_show_engine_status: '0',
    com_show_errors: '0',
    com_show_events: '0',
    com_show_explain: '0',
    com_show_analyze: '0',
    com_show_fields: '435',
    com_show_function_status: '0',
    com_show_generic: '0',
    com_show_grants: '2',
    com_show_keys: '72',
    com_show_binlog_status: '6',
    com_show_open_tables: '0',
    com_show_package_status: '0',
    com_show_package_body_status: '0',
    com_show_plugins: '0',
    com_show_privileges: '0',
    com_show_procedure_status: '0',
    com_show_processlist: '287',
    com_show_profile: '0',
    com_show_profiles: '0',
    com_show_relaylog_events: '0',
    com_show_slave_hosts: '0',
    com_show_slave_status: '6',
    com_show_status: '289',
    com_show_storage_engines: '2',
    com_show_table_status: '1',
    com_show_tables: '632',
    com_show_triggers: '0',
    com_show_variables: '337',
    com_show_warnings: '9',
    com_shutdown: '0',
    com_signal: '0',
    com_start_all_slaves: '0',
    com_start_slave: '0',
    com_stmt_close: '0',
    com_stmt_execute: '0',
    com_stmt_fetch: '0',
    com_stmt_prepare: '0',
    com_stmt_reprepare: '0',
    com_stmt_reset: '0',
    com_stmt_send_long_data: '0',
    com_stop_all_slaves: '0',
    com_stop_slave: '0',
    com_truncate: '0',
    com_uninstall_plugin: '0',
    com_unlock_tables: '0',
    com_update: '7',
    com_update_multi: '0',
    com_xa_commit: '0',
    com_xa_end: '0',
    com_xa_prepare: '0',
    com_xa_recover: '0',
    com_xa_rollback: '0',
    com_xa_start: '0',
    compression: 'OFF',
    connection_errors_accept: '0',
    connection_errors_internal: '0',
    connection_errors_max_connections: '0',
    connection_errors_peer_address: '0',
    connection_errors_select: '0',
    connection_errors_tcpwrap: '0',
    connections: '296',
    cpu_time: '0.000000',
    created_tmp_disk_tables: '619',
    created_tmp_files: '4',
    created_tmp_tables: '3080',
    delayed_errors: '0',
    delayed_insert_threads: '0',
    delayed_writes: '0',
    delete_scan: '0',
    empty_queries: '7436',
    executed_events: '0',
    executed_triggers: '0',
    feature_application_time_periods: '0',
    feature_check_constraint: '3',
    feature_custom_aggregate_functions: '0',
    feature_delay_key_write: '0',
    feature_dynamic_columns: '0',
    feature_fulltext: '0',
    feature_gis: '0',
    feature_insert_returning: '0',
    feature_invisible_columns: '0',
    feature_json: '4405',
    feature_locale: '124',
    feature_subquery: '12',
    feature_system_versioning: '0',
    feature_timezone: '0',
    feature_trigger: '0',
    feature_window_functions: '0',
    feature_xml: '0',
    handler_commit: '8161',
    handler_delete: '7',
    handler_discover: '0',
    handler_external_lock: '0',
    handler_icp_attempts: '0',
    handler_icp_match: '0',
    handler_mrr_init: '0',
    handler_mrr_key_refills: '0',
    handler_mrr_rowid_refills: '0',
    handler_prepare: '0',
    handler_read_first: '122',
    handler_read_key: '1416',
    handler_read_last: '0',
    handler_read_next: '255',
    handler_read_prev: '0',
    handler_read_retry: '0',
    handler_read_rnd: '1438',
    handler_read_rnd_deleted: '92',
    handler_read_rnd_next: '378301',
    handler_rollback: '3',
    handler_savepoint: '0',
    handler_savepoint_rollback: '0',
    handler_tmp_delete: '0',
    handler_tmp_update: '0',
    handler_tmp_write: '378693',
    handler_update: '12',
    handler_write: '23',
    innodb_adaptive_hash_hash_searches: '0',
    innodb_adaptive_hash_non_hash_searches: '0',
    innodb_background_log_sync: '112194',
    innodb_buffer_pool_dump_status: '',
    innodb_buffer_pool_load_status: 'Buffer pool(s) load completed at 250116 18:56:44',
    innodb_buffer_pool_resize_status: '',
    innodb_buffer_pool_load_incomplete: 'OFF',
    innodb_buffer_pool_pages_data: '1033',
    innodb_buffer_pool_bytes_data: '16924672',
    innodb_buffer_pool_pages_dirty: '209',
    innodb_buffer_pool_bytes_dirty: '3424256',
    innodb_buffer_pool_pages_flushed: '0',
    innodb_buffer_pool_pages_free: '251447',
    innodb_buffer_pool_pages_made_not_young: '0',
    innodb_buffer_pool_pages_made_young: '0',
    innodb_buffer_pool_pages_misc: '0',
    innodb_buffer_pool_pages_old: '385',
    innodb_buffer_pool_pages_total: '252480',
    innodb_buffer_pool_pages_lru_flushed: '0',
    innodb_buffer_pool_pages_lru_freed: '0',
    innodb_buffer_pool_read_ahead_rnd: '0',
    innodb_buffer_pool_read_ahead: '0',
    innodb_buffer_pool_read_ahead_evicted: '0',
    innodb_buffer_pool_read_requests: '10699',
    innodb_buffer_pool_reads: '858',
    innodb_buffer_pool_wait_free: '0',
    innodb_buffer_pool_write_requests: '1930',
    innodb_checkpoint_age: '118119',
    innodb_checkpoint_max_age: '80819529',
    innodb_data_fsyncs: '148',
    innodb_data_pending_fsyncs: '0',
    innodb_data_pending_reads: '0',
    innodb_data_pending_writes: '0',
    innodb_data_read: '14057472',
    innodb_data_reads: '985',
    innodb_data_writes: '127',
    innodb_data_written: '0',
    innodb_dblwr_pages_written: '0',
    innodb_dblwr_writes: '0',
    innodb_deadlocks: '0',
    innodb_history_list_length: '0',
    innodb_ibuf_discarded_delete_marks: '0',
    innodb_ibuf_discarded_deletes: '0',
    innodb_ibuf_discarded_inserts: '0',
    innodb_ibuf_free_list: '0',
    innodb_ibuf_merged_delete_marks: '0',
    innodb_ibuf_merged_deletes: '0',
    innodb_ibuf_merged_inserts: '0',
    innodb_ibuf_merges: '0',
    innodb_ibuf_segment_size: '2',
    innodb_ibuf_size: '1',
    innodb_log_waits: '0',
    innodb_log_write_requests: '1695',
    innodb_log_writes: '127',
    innodb_lsn_current: '4314923',
    innodb_lsn_flushed: '4314923',
    innodb_lsn_last_checkpoint: '4196804',
    innodb_master_thread_active_loops: '0',
    innodb_master_thread_idle_loops: '112194',
    innodb_max_trx_id: '4173',
    innodb_mem_adaptive_hash: '0',
    innodb_mem_dictionary: '27700440',
    innodb_os_log_written: '118103',
    innodb_page_size: '16384',
    innodb_pages_created: '175',
    innodb_pages_read: '858',
    innodb_pages_written: '0',
    innodb_row_lock_current_waits: '0',
    innodb_row_lock_time: '0',
    innodb_row_lock_time_avg: '0',
    innodb_row_lock_time_max: '0',
    innodb_row_lock_waits: '0',
    innodb_num_open_files: '125',
    innodb_truncated_status_writes: '0',
    innodb_available_undo_logs: '128',
    innodb_undo_truncations: '0',
    innodb_page_compression_saved: '0',
    innodb_num_pages_page_compressed: '0',
    innodb_num_page_compressed_trim_op: '0',
    innodb_num_pages_page_decompressed: '0',
    innodb_num_pages_page_compression_error: '0',
    innodb_num_pages_encrypted: '0',
    innodb_num_pages_decrypted: '0',
    innodb_have_lz4: 'OFF',
    innodb_have_lzo: 'OFF',
    innodb_have_lzma: 'OFF',
    innodb_have_bzip2: 'OFF',
    innodb_have_snappy: 'OFF',
    innodb_have_punch_hole: 'ON',
    innodb_defragment_compression_failures: '0',
    innodb_defragment_failures: '0',
    innodb_defragment_count: '0',
    innodb_instant_alter_column: '0',
    innodb_onlineddl_rowlog_rows: '0',
    innodb_onlineddl_rowlog_pct_used: '0',
    innodb_onlineddl_pct_progress: '0',
    innodb_encryption_rotation_pages_read_from_cache: '0',
    innodb_encryption_rotation_pages_read_from_disk: '0',
    innodb_encryption_rotation_pages_modified: '0',
    innodb_encryption_rotation_pages_flushed: '0',
    innodb_encryption_rotation_estimated_iops: '0',
    innodb_encryption_n_merge_blocks_encrypted: '0',
    innodb_encryption_n_merge_blocks_decrypted: '0',
    innodb_encryption_n_rowlog_blocks_encrypted: '0',
    innodb_encryption_n_rowlog_blocks_decrypted: '0',
    innodb_encryption_n_temp_blocks_encrypted: '0',
    innodb_encryption_n_temp_blocks_decrypted: '0',
    innodb_encryption_num_key_requests: '0',
    key_blocks_not_flushed: '0',
    key_blocks_unused: '107163',
    key_blocks_used: '0',
    key_blocks_warm: '0',
    key_read_requests: '0',
    key_reads: '0',
    key_write_requests: '0',
    key_writes: '0',
    last_query_cost: '0.000000',
    master_gtid_wait_count: '0',
    master_gtid_wait_time: '0',
    master_gtid_wait_timeouts: '0',
    max_statement_time_exceeded: '0',
    max_used_connections: '4',
    memory_used: '37775272',
    memory_used_initial: '35918528',
    not_flushed_delayed_rows: '0',
    open_files: '30',
    open_streams: '4',
    open_table_definitions: '72',
    open_tables: '49',
    opened_files: '2637',
    opened_plugin_libraries: '0',
    opened_table_definitions: '83',
    opened_tables: '59',
    opened_views: '94',
    optimizer_join_prefixes_check_calls: '3426',
    performance_schema_accounts_lost: '0',
    performance_schema_cond_classes_lost: '0',
    performance_schema_cond_instances_lost: '0',
    performance_schema_digest_lost: '0',
    performance_schema_file_classes_lost: '0',
    performance_schema_file_handles_lost: '0',
    performance_schema_file_instances_lost: '0',
    performance_schema_hosts_lost: '0',
    performance_schema_index_stat_lost: '0',
    performance_schema_locker_lost: '0',
    performance_schema_memory_classes_lost: '0',
    performance_schema_metadata_lock_lost: '0',
    performance_schema_mutex_classes_lost: '0',
    performance_schema_mutex_instances_lost: '0',
    performance_schema_nested_statement_lost: '0',
    performance_schema_prepared_statements_lost: '0',
    performance_schema_program_lost: '0',
    performance_schema_rwlock_classes_lost: '0',
    performance_schema_rwlock_instances_lost: '0',
    performance_schema_session_connect_attrs_lost: '0',
    performance_schema_socket_classes_lost: '0',
    performance_schema_socket_instances_lost: '0',
    performance_schema_stage_classes_lost: '0',
    performance_schema_statement_classes_lost: '0',
    performance_schema_table_handles_lost: '0',
    performance_schema_table_instances_lost: '0',
    performance_schema_table_lock_stat_lost: '0',
    performance_schema_thread_classes_lost: '0',
    performance_schema_thread_instances_lost: '0',
    performance_schema_users_lost: '0',
    prepared_stmt_count: '0',
    qcache_free_blocks: '1',
    qcache_free_memory: '1031344',
    qcache_hits: '0',
    qcache_inserts: '0',
    qcache_lowmem_prunes: '0',
    qcache_not_cached: '0',
    qcache_queries_in_cache: '0',
    qcache_total_blocks: '1',
    queries: '12057',
    questions: '12057',
    resultset_metadata_skipped: '0',
    rows_read: '955',
    rows_sent: '347384',
    rows_tmp_read: '376633',
    rpl_semi_sync_master_clients: '0',
    rpl_semi_sync_master_get_ack: '0',
    rpl_semi_sync_master_net_avg_wait_time: '0',
    rpl_semi_sync_master_net_wait_time: '0',
    rpl_semi_sync_master_net_waits: '0',
    rpl_semi_sync_master_no_times: '0',
    rpl_semi_sync_master_no_tx: '0',
    rpl_semi_sync_master_request_ack: '0',
    rpl_semi_sync_master_status: 'OFF',
    rpl_semi_sync_master_timefunc_failures: '0',
    rpl_semi_sync_master_tx_avg_wait_time: '0',
    rpl_semi_sync_master_tx_wait_time: '0',
    rpl_semi_sync_master_tx_waits: '0',
    rpl_semi_sync_master_wait_pos_backtraverse: '0',
    rpl_semi_sync_master_wait_sessions: '0',
    rpl_semi_sync_master_yes_tx: '0',
    rpl_semi_sync_slave_send_ack: '0',
    rpl_semi_sync_slave_status: 'OFF',
    rpl_status: 'AUTH_MASTER',
    rpl_transactions_multi_engine: '0',
    select_full_join: '34',
    select_full_range_join: '0',
    select_range: '0',
    select_range_check: '0',
    select_scan: '3048',
    slave_connections: '0',
    slave_heartbeat_period: '0.000',
    slave_open_temp_tables: '0',
    slave_received_heartbeats: '0',
    slave_retried_transactions: '0',
    slave_running: 'OFF',
    slave_skipped_errors: '0',
    slaves_connected: '0',
    slaves_running: '0',
    slow_launch_threads: '0',
    slow_queries: '0',
    sort_merge_passes: '0',
    sort_priority_queue_sorts: '0',
    sort_range: '0',
    sort_rows: '1438',
    sort_scan: '151',
    ssl_accept_renegotiates: '0',
    ssl_accepts: '0',
    ssl_callback_cache_hits: '0',
    ssl_cipher: '',
    ssl_cipher_list: '',
    ssl_client_connects: '0',
    ssl_connect_renegotiates: '0',
    ssl_ctx_verify_depth: '0',
    ssl_ctx_verify_mode: '0',
    ssl_default_timeout: '0',
    ssl_finished_accepts: '0',
    ssl_finished_connects: '0',
    ssl_server_not_after: '',
    ssl_server_not_before: '',
    ssl_session_cache_hits: '0',
    ssl_session_cache_misses: '0',
    ssl_session_cache_mode: 'NONE',
    ssl_session_cache_overflows: '0',
    ssl_session_cache_size: '0',
    ssl_session_cache_timeouts: '0',
    ssl_sessions_reused: '0',
    ssl_used_session_cache_entries: '0',
    ssl_verify_depth: '0',
    ssl_verify_mode: '0',
    ssl_version: '',
    subquery_cache_hit: '0',
    subquery_cache_miss: '0',
    syncs: '79',
    table_locks_immediate: '288',
    table_locks_waited: '0',
    table_open_cache_active_instances: '1',
    table_open_cache_hits: '8929',
    table_open_cache_misses: '153',
    table_open_cache_overflows: '0',
    tc_log_max_pages_used: '0',
    tc_log_page_size: '0',
    tc_log_page_waits: '0',
    threadpool_idle_threads: '0',
    threadpool_threads: '3',
    threads_cached: '0',
    threads_connected: '3',
    threads_created: '47',
    threads_running: '1',
    transactions_gtid_foreign_engine: '0',
    transactions_multi_engine: '0',
    update_scan: '0',
    uptime: '826161',
    uptime_since_flush_status: '826161'
  } */